import fs from 'node:fs';
import path from 'node:path';
export const genres=['J-pop','K-pop','애니메이션','보컬로이드','기타'];
export const normalize=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
const artistAliases={
 'DAY6 데이식스':'DAY6','DAY6(데이식스)':'DAY6','블랙핑크 (BLACKPINK)':'BLACKPINK','뉴진스':'NewJeans','태연':'TAEYEON','여자친구':'GFRIEND','BoA (보아)':'BoA','아이유(IU)':'IU','요루시카 (ヨルシカ)':'ヨルシカ','요루시카(ヨルシカ)':'ヨルシカ','유우리 優里':'優里','이키모노가카리 いきものがかり':'いきものがかり','프리데릭 (フリデリック)':'フレデリック','라르크 앙 시엘 (L\'Arc en Ciel)':'L’Arc〜en〜Ciel','T.M.revolution':'T.M.Revolution','마츠다 세이코 (松田聖子)':'松田聖子','마츠바라미키':'松原みき','시이나 링고':'椎名林檎','사잔 올 스타즈 (サザンオールスターズ)':'サザンオールスターズ','모닝구무스메(モ-ニング娘)':'モーニング娘。','골든 봄버 (Golden Bomber)':'ゴールデンボンバー','요네즈 켄시 (米津玄師)':'米津玄師','米津玄師 (요네즈켄시)':'米津玄師','미즈키나나 (水樹奈々)':'水樹奈々','히라노 아야':'平野綾','나카시마 미카':'中島美嘉','레오나(ReoNa)':'ReoNa','쿠라키마이 倉木麻衣':'倉木麻衣','요네쿠라 치히로(米倉千尋)':'米倉千尋','요네쿠라 치히로 (米倉千尋)':'米倉千尋','하야시바라 메구미 (林原めぐみ)':'林原めぐみ','타마키 나미 (玉置成実)':'玉置成実','호리에 유이':'堀江由衣','타카하시 리에':'高橋李依','녹황색사회':'緑黄色社会','나카지마 메구미':'中島愛','쿠리바야시 미나미':'栗林みな実','미키토p':'みきとP','みきとP (미키토)':'みきとP','유유 (feat. 카가미네 린)':'ゆうゆ','ジミーサムP (지미섬)':'ジミーサムP','뮤즈':'μ’s','나인뮤지스 (9muses)':'9MUSES','오렌지 캬라멜':'Orange Caramel','위너 (winner)':'WINNER','방탄소년단 (BTS)':'BTS','로맨틱펀치':'Romantic Punch','린':'LYn','네미시스':'Nemesis','LUCY (루시)':'LUCY','박봄 (Park bom)':'Park Bom','아지캉 ASIAN KUNG-FU GENERATION':'ASIAN KUNG-FU GENERATION','이용신':'이용신','이수영':'이수영','인피니트':'INFINITE','tripleS(트리플에스)':'tripleS','리센느 (RESCENE)':'RESCENE','김재중':'JAEJOONG','윤하':'YOUNHA','모리타카 치사코 (森森高千里)':'森高千里','Noa (乃紫)':'乃紫','CHiCO Honeyworks':'CHiCO with HoneyWorks','ヒナタ メグミ':'日向めぐみ','히나타 메구미':'グミ','ANNA tsuchiya':'土屋アンナ','BULGE':'島谷ひとみ','코마츠 리카':'小松里歌','아야미야 제로':'相宮零','아마츠키 (天月) Feat. HoneyWorks':'天月','きゃりーぱみゅぱみゅ (캬리 파뮤파뮤)':'きゃりーぱみゅぱみゅ'};
const titleAliases={
 '한 페이지가 될 수 있게':['Time of Our Life'],'드라이 플라워':['ドライフラワー'],'마루노우치 새디스틱':['丸の内サディスティック'],'만찬가':['晩餐歌'],'푸른 산호초':['青い珊瑚礁'],'사랑 감기에 실려':['恋風邪にのせて'],'작은 사랑의 노래':['小さな恋のうた'],'첫사랑 킬러':['初恋キラー'],'천국의 키스 (天国きのキッス)':['天国のキッス'],'바람은 가을색 (風邪は秋色)':['風は秋色'],'귀여워서 미안해':['可愛くてごめん'],'금요일의 아침인사':['金曜日のおはよう'],'벚꽃만월':['サクラミツツキ'],'사무라이하트':['サムライハート(Some Like It Hot!!)'],'실루엣':['シルエット'],'잔혹한 천사의 테제':['残酷な天使のテーゼ'],'카타오모이 (짝사랑 カタオモイ)':['カタオモイ'],'그대라는 시':['All About You'],'오르트구름':['Oort Cloud'],'까탈레나':['Catallena'],'불장난':['PLAYING WITH FIRE'],'휘파람':['WHISTLE'],'그리워해요':['Missing You'],'내꺼하자':['Be Mine'],'나는 아픈건 딱 질색이니까':['Fate'],'상남자 (boy in luv)':['Boy In Luv'],'짧은치마(Miniskirt)':['Miniskirt'],'단발머리(Short Hair)':['Short Hair'],'열대야(Fever)':['Fever'],'불티 (Spark)':['Spark'],'사계':['Four Seasons'],'뉴스 (news)':['News'],'돌스(Dolls)':['Dolls'],'날개를 주세요 (翼をください)':['翼をください'],'아이돌 활동 (アイドル活動！)':['アイドル活動!'],'이름을 부를게 (名前を呼ぶよ)':['名前を呼ぶよ'],'꽃에망령':['花に亡霊'],'사랑의 시나리오':['アイのシナリオ'],'오렌지':['オレンジ'],'나츠마츠리 (夏祭り)':['夏祭り'],'God knows…':['God knows...'],'you':['you'],'루카루카 나이트 피버 (ルカルカ★ナイトフィーバー)':['ルカルカ★ナイトフィーバー'],'모자이크롤':['モザイクロール'],'사리시노하라':['サリシノハラ'],'소녀레이':['少女レイ'],'천악 (天樂)':['天樂'],'춤춰라 오케스트라':['踊れオーケストラ']};
export function artistQuery(song){const raw=song.artist.includes('/')?song.artist.split('/').at(-1).trim():song.artist.trim();return artistAliases[raw]||raw.replace(/\([^)]*\)/g,'').trim()||song.title;}
Object.assign(titleAliases,{
 'lovers':['ラヴァーズ'],'Orange':['オレンジ'],'Odoloop':['オドループ'],'Blue Bird':['ブルーバード'],'Connect':['コネクト'],'Departures ~당신에게 보내는 사랑의 노래~':['Departures ~あなたにおくるアイの歌~'],'로미오와 신데렐라':['ロミオとシンデレラ'],'메메시쿠테 (소심해서 女々しくて)':['女々しくて'],'나의 마음을 담아':['With my Heart'],'나의 마음을 담아 (acoustic ver.)':['With my Heart (Acoustic Version)'],'시간을 거슬러':['Back In Time'],'아잉♡':['Aing♡'],'오늘부터 우리는 (Me Gustas Tu)':['Me Gustas Tú'],'제주도의 푸른밤':['The Blue Night of Jeju Island'],'있잖아(Rock Ver.)':['You Know (Rock Version)'],'거짓말(uso)':['嘘'],'라이온':['ライオン'],'Invoke':['INVOKE -インヴォーク-'],'secret base':['secret base 〜君がくれたもの〜'],'花になって (꽃이 되어줘)':['花になって - Be a flower']
});
const artistEquivalents={
 '이용신':['Lee Yong Shin'],'이수영':['Lee Soo Young'],'전영록':['Jeon Young Rok'],'다비치':['DAVICHI'],'디오지':['DOZ'],'베스티':['BESTie'],'동방신기':['TVXQ!'],'JAEJOONG':['ジェジュン'],'아이들':['i-dle','(G)I-DLE'],'7!!':['7!!(セブンウップス)'],'tuki':['tuki.'],'YASUHIRO ft. IA':['YASUHIRO(康寛)'],'小松里歌':['小松里賀','Rika Komatsu'],'케이온':['桜高軽音部','放課後ティータイム'],'아이카츠 !':['わか・ふうり・すなお from STAR☆ANIS','わか・ふうり from STAR☆ANIS'],'釘宮理恵,堀江由衣,喜多村英梨':['逢坂大河(釘宮理恵), 櫛枝実乃梨(堀江由衣) & 川嶋亜美(喜多村英梨)'],'장숙희,정여진':['장숙희 & Jung Yeo Jin','장숙희, 김문선 & 정여진'],'프리스타일':['Freestyle']
};
Object.assign(titleAliases,{
 '마루노우치 새디스틱':['丸ノ内サディスティック'],'만찬가':['晩餐歌 - Bansanka'],'못죽는 기사와 비단요람':["The knight who can't die and the silk cradle"],'몽유병':['Sleepwalk'],'베르사유의 장미':['The Rose of Versailles'],'연애의조건':['Love Options'],'토요일 밤이 좋아':['Saturday Night Fever'],'Y':['Y (Please Tell Me Why)'],'Polaris':['ポラリス'],'catch you catch me':['Catch You Catch Me [From "Cardcaptor Sakura" (Original Soundtrack)] [2026 Remastered Version]']
});
Object.assign(artistEquivalents,{'グミ':['GUMI'],'土屋アンナ':["ANNA TSUCHIYA inspi' NANA(BLACK STONES)"]});
export function names(song){return [...new Set([song.title,...(titleAliases[song.title]||[]),...song.title.split(/\s*[|/]\s*/),...Array.from(song.title.matchAll(/[（(]([^）)]+)[）)]/g),m=>m[1]),song.title.replace(/[（(][^）)]*[）)]/g,'').trim()])];}
export function candidateScore(song,t){
 const n=normalize(t.trackName),base=normalize(t.trackName.replace(/\s+(?:feat[. ]|\(feat[. ]).*$/i,''));
 const title=Math.max(...names(song).map(s=>{s=normalize(s);return s===n||s===base?1:s.length>3&&n.includes(s)?.8:0;}));
 const query=artistQuery(song),actual=normalize(t.artistName);
 const artist=[query,...(artistEquivalents[query]||[])].some(a=>{a=normalize(a);return a===actual||a.length>2&&(actual.includes(a)||a.includes(actual));});
 const version=/acoustic|rockver/i.test(song.title)?/acoustic|rock/i.test(t.trackName):!/(?:instrumental|\(inst\.\)|karaoke|オルゴール|カラオケ)/i.test(t.trackName);
 return title*(artist?1:.35)*(version?1:.6);
}
export function loadSongs(root){const local=root&&path.join(root,'data','songbook.raw.json');const rows=JSON.parse(fs.readFileSync(local&&fs.existsSync(local)?local:new URL('../data/songbook.raw.json',import.meta.url),'utf8'));return rows.map(([id,g,title,artist='',...notes])=>({id,title:title.normalize('NFC'),artist:artist.normalize('NFC'),notes,genres:g.split(',').map(i=>genres[Number(i)]),sourceUrl:`https://app.notion.com/p/${id}`}));}
