import {pathToFileURL,fileURLToPath} from 'node:url';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=await import(pathToFileURL('C:/Users/legen/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'));
const base='https://kira-setlist-web.vercel.app';
const created=await fetch(base+'/api?op=rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(created.status,201);const credentials=await created.json();
const call=async(op,data,token=credentials.owner)=>{const r=await fetch(base+'/api?'+new URLSearchParams({op,room:credentials.room}),{headers:{Authorization:`Bearer ${token}`,...(data?{'Content-Type':'application/json'}:{})},...(data?{method:'POST',body:JSON.stringify(data)}:{})});return {status:r.status,data:await r.json()};};
const catalog=await (await fetch(base+'/catalog.json')).json();assert.equal(catalog.length,211);
let state;
for(const title of ['Amazing kiss','ANGELUS (アンジェラス)','Calc']){const song=catalog.find(s=>s.title===title);assert.ok(song,title);const r=await call('action',{type:'add',songId:song.id});assert.equal(r.status,200,JSON.stringify(r.data));state=r.data;}
const started=await call('action',{type:'start',id:state.queue[0].id});assert.equal(started.status,200);
assert.equal((await call('action',{type:'clear'},credentials.view)).status,403);
assert.equal((await call('export',null,credentials.view)).status,403);
assert.equal((await call('state',null,'wrong-key')).status,403);
const browser=await chromium.launch({channel:'msedge',headless:true});
const ownerContext=await browser.newContext({viewport:{width:530,height:1080}}),viewerContext=await browser.newContext({viewport:{width:1920,height:1080}});
const owner=await ownerContext.newPage(),viewer=await viewerContext.newPage();const errors=[];owner.on('pageerror',e=>errors.push(e.message));viewer.on('pageerror',e=>errors.push(e.message));
await owner.goto(base+'/control?dock=1#'+new URLSearchParams({room:credentials.room,owner:credentials.owner,view:credentials.view}));
await viewer.goto(base+'/overlay?preview=1#'+new URLSearchParams({room:credentials.room,view:credentials.view}));
const frame=()=>viewer.frameLocator('#edition-frame');
await frame().locator('#song-title').filter({hasText:'Amazing kiss'}).waitFor();
await owner.locator('#complete').click();
await frame().locator('#song-title').filter({hasText:'ANGELUS (アンジェラス)'}).waitFor();
await owner.locator('[data-edition=original]').click();
await viewer.waitForFunction(()=>document.querySelector('#edition-frame').src.includes('/original/'));
await frame().locator('#song-title').filter({hasText:'ANGELUS (アンジェラス)'}).waitFor();
await owner.locator('[data-edition=amp]').click();
await viewer.waitForFunction(()=>document.querySelector('#edition-frame').src.includes('/amp/'));
await frame().locator('#song-title').filter({hasText:'ANGELUS (アンジェラス)'}).waitFor();
await owner.locator('#open-custom').click();await owner.locator('#custom-title').fill('직접 등록 확인');await owner.locator('#custom-artist').fill('웹 테스트');await owner.locator('#custom-submit').click();await owner.locator('#custom-dialog').waitFor({state:'hidden'});
assert.equal((await call('state')).data.queue.length,4);
await owner.reload();await owner.locator('#queue-count').filter({hasText:'4'}).waitFor();
await fs.mkdir(new URL('../test-results/',import.meta.url),{recursive:true});
await owner.screenshot({path:fileURLToPath(new URL('../test-results/web-dock.png',import.meta.url)),fullPage:true});
await viewer.screenshot({path:fileURLToPath(new URL('../test-results/web-amp.png',import.meta.url))});
await owner.locator('[data-edition=original]').click();await viewer.waitForFunction(()=>document.querySelector('#edition-frame').src.includes('/original/'));await frame().locator('#song-title').filter({hasText:'ANGELUS (アンジェラス)'}).waitFor();
await viewer.screenshot({path:fileURLToPath(new URL('../test-results/web-original.png',import.meta.url))});
await owner.locator('[data-edition=amp]').click();
const landing=await ownerContext.newPage();await landing.goto(base);assert.equal(await landing.locator('#create-room').isVisible(),true);assert.equal(await landing.locator('.examples img').evaluate(el=>el.complete&&el.naturalWidth>0),true);
assert.deepEqual(errors,[]);
console.log('PASS: public access, 211 songs, persisted room, separate browser profiles synchronize, next song, original/DLC switch, manual add, reload persistence, viewer authorization.');
await browser.close();
